### ISSUE TITLE
Parametrize with optparse

### ISSUE THREAD

**Issue by pbanaszkiewicz** [prerit2010/swc-setup-installation-test#1]
It would be good for users to be able to specify:
1. `-h HOST` command line argument
2. `dependency1 dependency2` as it was before

I was going to propose to use argparse, but it's only available in Python 3.2+.

**Comment by pbanaszkiewicz** [comment]
Perhaps there are other things we might want to parametrize, so think about it.

**Comment by prerit2010** [comment]
@pbanaszkiewicz  like : `python swc-installation-test-2.py -h 127.0.0.1` right ?

**Comment by pbanaszkiewicz** [comment]
Yes. Also something like `--no-reporting` to turn sending data to the 
server off.

**Comment by prerit2010** [comment]
Hmm that's Cool.

**Comment by rgaiacs** [comment]
> I was going to propose to use argparse, but it's only available in Python 3.2+.

I thought that we were using Python3 now.

**Comment by pbanaszkiewicz** [comment]
@rgaiacs yeah I think you're right, I think we're running our workshops on Python3. However the scripts are prepared to work with Python2.7+ (see https://github.com/prerit2010/swc-setup-installation-test/blob/master/swc-installation-test-1.py#L45), so I don't know. Should we port them to Python3?

**Comment by rgaiacs** [comment]
> I was going to propose to use argparse, but it's only available in Python 3.2+.

argparse works with Python2, see https://docs.python.org/2/howto/argparse.html. The previous link only mention that

> A few details are different in 2.x, especially some exception messages, which were improved in 3.x.

I don't think we are going to need those.
