### ISSUE TITLE
Hide/rename the key file

### ISSUE THREAD

**Issue by pbanaszkiewicz** [prerit2010/swc-setup-installation-test#5]
Currently the `key.txt` is visible in Linux (and I think OS X as well?).

Personally I'd call it `.swc_submission_id` so that:
1. it doesn't sound like it contains some secret
2. it doesn't overwrite persons important `key.txt` file
3. it clearly belongs to the Software-Carpentry
4. it's hidden on Linux and perhaps OS X as well

**Comment by prerit2010** [comment]
Yeah! That'll be good. Thanks. :)
