### ISSUE TITLE
TypeError: normcase() argument must be str or bytes, not 'NoneType'

### ISSUE THREAD

**Issue by rgaiacs** [prerit2010/swc-setup-installation-test#7]
```
$ Python 3.5.1 :: Continuum Analytics, Inc.
$ python swc-installation-test-2.py
...
Argparse (argparse) 1.1

Failures:

Traceback (most recent call last):
  File "swc-installation-test-2.py", line 1126, in <module>
    passed, successes_list, failures_list = check(args)
  File "swc-installation-test-2.py", line 295, in check
    print(failure)
  File "swc-installation-test-2.py", line 242, in __str__
    url = self.get_url()
  File "swc-installation-test-2.py", line 232, in get_url
    _fnmatch.fnmatch(version, v) and
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/fnmatch.py", line 34, in fnmatch
    name = os.path.normcase(name)
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/posixpath.py", line 54, in normcase
    "not '{}'".format(s.__class__.__name__))
TypeError: normcase() argument must be str or bytes, not 'NoneType'
```

**Comment by prerit2010** [comment]
@rgaiacs I'm not sure why is this error coming up, and how to reproduce this error. It's coming in the piece of code that was written already. May be wking can provide insight on it.

**Comment by rgaiacs** [comment]
@wking Do you have comments?

**Comment by wking** [comment]
On Tue, Jul 05, 2016 at 02:34:36AM -0700, Raniere Silva wrote:

> @wking Do you have comments?

That get_url code is trying to find system/version information [1](https://github.com/wking/swc-setup-installation-test/blob/74844ea43e4df102d9013eae92d19f7f924ee00b/swc-installation-test-2.py#L217-L232).
Tracebacks targetting parenthesis-extended lines can be tricky, but if
it's really the _fnmatch.fnmatch(version, v) line that's failing, it
means we're finishing the loop without having found ‘version’ (this
should probably get its own error for less cryptic tracebacks).  To
patch this issue though, I'll need to know what platform the traceback
was generated on, so we can figure out what to add to the pversion
loop.

**Comment by rgaiacs** [comment]
@wking Thanks very much for the information.

```
$ uname -a
Linux ssi 4.6.2-1-MANJARO #1 SMP PREEMPT Wed Jun 8 11:00:08 UTC 2016 x86_64 GNU/Linux
```

**Comment by wking** [comment]
On Tue, Jul 05, 2016 at 09:36:46AM -0700, Raniere Silva wrote:

> Linux ssi 4.6.2-1-MANJARO #1 SMP PREEMPT Wed Jun 8 11:00:08 UTC 2016
> x86_64 GNU/Linux

Maybe Python can't find the distribution info?  On my system:

  $ python -c 'import platform; print(platform.linux_distribution())' 
  ('Gentoo Base System', '2.2', '')

and stracing that turns up opens for /etc and /etc/gentoo-release (I'm
surprised it isn't looking at the more generic /etc/os-release,
although I guess that doesn't have version information).

What distribution are you running, and what *release stuff is in /etc?

**Comment by pbanaszkiewicz** [comment]
Seems like [Manjaro](http://manjaro.github.io/about/), an Arch Linux offspring.

**Comment by wking** [comment]
On Sat, Jul 09, 2016 at 11:41:34PM -0700, Piotr Banaszkiewicz wrote:

> Seems like [Manjaro](http://manjaro.github.io/about/), an Arch Linux
> offspring.

Then they likely have Python compiled from scratch, so I'm not sure
how they're missing platform.linux_distribution [1](https://docs.python.org/3/library/platform.html#platform.linux_distribution).

However, looking at the docs again that method is currently deprecated
to be removed in 3.7.  The motivation for that seems to be “this is
complicated” [2](http://bugs.python.org/issue1322#msg134255) ;).  I'll patch the installation-test scripts to
handle this more gracefully, and to the replacement PyPI package [3](http://bugs.python.org/issue1322#msg263896)
if it happens to be installed.

**Comment by wking** [comment]
On Sun, Jul 10, 2016 at 02:41:41PM -0700, W. Trevor King wrote:

> I'll patch the installation-test scripts to handle this more
> gracefully, and to the replacement PyPI package [3] if it happens to
> be installed.

Done in wking/swc-setup-installation-test#13 if anyone wants to kick
the tires.
